name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target x86_64-unknown-linux-musl
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --target x86_64-unknown-linux-musl
